#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
CREATE USER $APP_DB_USER WITH PASSWORD '$APP_DB_PASSWORD';
CREATE SCHEMA $APP_DB_SCHEMA;
GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $APP_DB_USER;
GRANT ALL ON SCHEMA $APP_DB_SCHEMA to $APP_DB_USER;
GRANT USAGE, CREATE ON SCHEMA $APP_DB_SCHEMA TO $APP_DB_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA $APP_DB_SCHEMA TO $APP_DB_USER;
CREATE SEQUENCE account_sequence START WITH 1 INCREMENT BY 1;
EOSQL