services:
  db:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
      - .:/project
      - ps_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  ps_data: