version: '3.5'

services:
  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./set-up-local-db.sql:/docker-entrypoint-initdb.d/init-db.sql

#volumes:
#  postgres-data: