INSERT INTO TRANSACTIONS
(TRANSACTION_ID, SOURCE_ACCOUNT_ID, DESTINATION_ACCOUNT_ID, AMOUNT, ACTION_DATE)
 VALUES
(NEXTVAL('transaction_sequence'), :sourceAccountId, :destinationAccountId, amount, actionDate)
RETURNING TRANSACTION_ID;